# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: MyAgent

variables:
  tag: $(Build.BuildId)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker registry'
    repository: 'suruthi125/newone'
    command: 'buildAndPush'
    Dockerfile: './frontend/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'docker registry'
    repository: 'suruthi125/newone'
    command: 'run'
    arguments: '-d -p 3000:3000 suruthi125/newone:$(tag)'
  
