# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and push docker 
    jobs:
      - job: Build 
        displayName: Build and push image
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker registry'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
  # - stage: Deploy
  #   displayName: Deploy stage 
  #   jobs:
  #     - job:
  #       displayName: docker deploy
  #       steps:
  #       - task: AzureRmWebAppDeployment@4
  #         inputs:
  #           ConnectionType: 'AzureRM'
  #           appType: 'webApp'
  #           WebAppName: 
  #           packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
          
