# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: MyAgent

stages:
  - stage: Build
    displayName: Build and push docker 
    jobs:
      - job: Build 
        displayName: Build and push image
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'docker registry'
            Repository: 'suruthi125/new one'
            command: 'buildAndPush'
            Dockerfile: './frontend/Dockerfile'
  
